plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    compileSdk 36
    namespace 'land.sungbin.androidplayground'

    defaultConfig {
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = '21'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin/'
    }
}

dependencies {
    implementation 'androidx.activity:activity-compose:1.11.0'
    implementation 'androidx.compose.foundation:foundation:1.12.0'
}
